num1 = int(input("Digite o primeiro numero: "))
num2 = int(input("Digite o segundo numero: "))
num3 = int(input("Digite o terceiro numero: "))
calculo = (num1 * num2 * num3)
print("A multiplicação dos numeros é: ", calculo)